name = "Graphics"
uuid = "a2bd30eb-e257-5431-a919-1863eab51364"
version = "1.1.3"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"

[compat]
Colors = "0.9, 0.10, 0.11, 0.12, 0.13"
NaNMath = "0.3.3, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
