name = "NetCDF_jll"
uuid = "7243133f-43d8-5620-bbf4-c2c921802cf3"
version = "401.900.300+0"

[deps]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
libaec_jll = "477f73a3-ac25-53e9-8cc3-50b2fa2566f0"
Blosc_jll = "0b7ba130-8d10-5ba8-a3d6-c5182647fed9"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
HDF5_jll = "0234f1f7-429e-5d53-9886-15a909be8d59"
MPICH_jll = "7cb0a576-ebde-5e09-9194-50597f1243b4"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
XML2_jll = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
LibCURL_jll = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
MPItrampoline_jll = "f1f71cc9-e9ae-5b93-9b94-4fe0e1ad3748"
libzip_jll = "337d8026-41b4-5cde-a456-74a10e5b31d1"
OpenMPI_jll = "fe0851c0-eecd-5654-98d4-656369965a5c"
Zstd_jll = "3161d3a3-bdf6-5164-811a-617609db77b4"
MicrosoftMPI_jll = "9237b28f-5490-5468-be7b-bb81f5f5e6cf"

[compat]
MPIPreferences = "0.1"
Zlib_jll = "1.2.12"
libaec_jll = "1.1.3"
Blosc_jll = "1.21.6"
Libdl = "< 0.0.1, 1"
LazyArtifacts = "< 0.0.1, 1"
HDF5_jll = "~1.14.6"
JLLWrappers = "1.7.0"
MPICH_jll = "4.3.0 - 4"
Bzip2_jll = "1.0.9"
XML2_jll = "2.13.6"
Artifacts = "< 0.0.1, 1"
julia = "1.6"
LibCURL_jll = "7.73.0,8"
MPItrampoline_jll = "5.5.3 - 5"
libzip_jll = "1.11.3"
OpenMPI_jll = "4.1.8, 5.0.7"
Zstd_jll = "1.5.7"
TOML = "< 0.0.1, 1"
