name = "Rmath"
uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
version = "0.8.2"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rmath_jll = "f50d1b31-88e8-58de-be2c-1cc44531875f"

[compat]
Random = "<0.0.1, 1"
Aqua = "0.8"
Test = "<0.0.1, 1"
Statistics = "<0.0.1, 1"
Rmath_jll = "0.4, 0.5"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Statistics", "Test"]
