name = "Showoff"
uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
author = ["Daniel C. Jones (@dcjones)"]
version = "1.0.3"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Grisu = "42e2da0e-8278-4e71-bc24-59509adca0fe"

[compat]
Grisu = "1"
julia = "1"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[targets]
test = ["Dates", "Test", "Printf"]
