name = "Netpbm"
uuid = "f09324ee-3d7c-5217-9330-fc30815ba969"
version = "1.1.1"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageMetadata = "bc367c6b-8a6b-528e-b4bd-a4b897500b49"

[compat]
FileIO = "1"
ImageCore = "0.9, 0.10"
ImageMetadata = "0.9"
julia = "1"

[extras]
IndirectArrays = "9b13fd28-a010-5f03-acff-a1bbcff69959"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "IndirectArrays", "OffsetArrays"]
