[soilgrids]
git-tree-sha1 = "f919da748cc973519fb136f4225cf343f5c3e41f"
[soilgrids_lowres]
git-tree-sha1 = "6ce1717bb8b7aa767380f1053b9d8d3a4e4edaa6"

    [[soilgrids_lowres.download]]
    sha256 = "27d49fce7f4a5e2b81bbd29e8a7caf08f568a2df53e3af817126363decfd5a7c"
    url = "https://caltech.box.com/shared/static/99aw2gce2k65bdu0h8jkfxq4vin08gi2.gz"

[sw_albedo]
git-tree-sha1 = "136f1db3ed969614fb589c5250545a3ed1e8aaab"

    [[sw_albedo.download]]
    sha256 = "777371543cc3285c0779e7ecd925fe782b5b45e0ed27f82260827ac8ebe6a700"
    url = "https://caltech.box.com/shared/static/of1admpndmikoumtgk5j3yvt92v71awk.gz"

[clm_data]
git-tree-sha1 = "3f6873a3e67722bda1fd23f7d5a05f5e2df1fe8c"

    [[clm_data.download]]
    sha256 = "830136abec15551a343b7884d657fb6a79b16a37237681a2becf65bd845aa692"
    url = "https://caltech.box.com/shared/static/6pu2f6c99g29qawvjjh3j56drkonpd3z.gz"

[era5_land_forcing_data2008]
git-tree-sha1 = "93d2e93f491e77cb8fba2a1b8b3946f38bde469e"
[era5_land_forcing_data2008_lowres]
git-tree-sha1 = "fd826542e6ab1758c8d5a2cc6dbf1f67b47aadee"

    [[era5_land_forcing_data2008_lowres.download]]
    sha256 = "c5ea5acfcab2e69c26d6ef8ba20e9e6dc018e5baa9c48d0df69cf0a5f9bf3399"
    url = "https://caltech.box.com/shared/static/6zk5fa3ka5ib62jsrs6tx35sqwe8xv2k.gz"
[era5_land_forcing_data2008_lai]
git-tree-sha1 = "df5ec5af1ea0793c0e7d49e60db5a938098e174f"

    [[era5_land_forcing_data2008_lai.download]]
    sha256 = "a83bf28a7a864db285e41289031a9761c2a426373a6efecd04b866a0b5374cef"
    url = "https://caltech.box.com/shared/static/m82r23e67x04a3hb6p79dfltlumvg9z0.gz"

[modis_lai]
git-tree-sha1 = "20ee5dc96fde9a15bd3c40e80ac5036a9a39e0cf"

    [[modis_lai.download]]
    sha256 = "e97bf4a8eeac7c32c00a7d27bf5ec957e9c800117d56e66c27a123171a1f1c04"
    url = "https://caltech.box.com/shared/static/99ktg026kciezykyegsawd1gjwj1du74.gz"

[land_albedo]
git-tree-sha1 = "3f07b70ab43a05123e93753a45e094dcf7a66b5b"

[snowmip]
git-tree-sha1 = "230f00823299e7e33d276d9b57cba985fc04eaae"

    [[snowmip.download]]
    sha256 = "598b525c7421fabf06de4c8d4d7e05d50b7655ad2387d98c4335e90fd5633d61"
    url = "https://caltech.box.com/shared/static/0vqhet1hsj36sgmy0ajrcrb24cihcfd7.gz"

[soil_params_Gupta2020_2022]
git-tree-sha1 = "c10e8f877603bfa2c018eb2dd0c51dd078abe5df"

    [[soil_params_Gupta2020_2022.download]]
    sha256 = "6205d96ae7724c469eef5cd1cf3b99e186637427b6fb65ecc659fb808fc6cacf"
    url = "https://caltech.box.com/shared/static/7c6yx62tzjivxfmhqyy03r6e9l1glyu1.gz"

[modis_clumping_index]
git-tree-sha1 = "b849eb95c09190095e7bf021494ddeda8858af01"

    [[modis_clumping_index.download]]
    sha256 = "e4c766a93a673e5dc22540687ef5616416d65bb13a0f4a67789b95d49ccbb158"
    url = "https://caltech.box.com/shared/static/ec2y3k5kqpl9wjvtsx3584wgkp5q8dyw.gz"

[bonan_richards_eqn]
git-tree-sha1 = "043f9354b961fd3ef6ac4cf71d0c99930e177a92"
    [[bonan_richards_eqn.download]]
    sha256 = "50f1739dfd8193742488f249bd1ba8a157dfc7c1d8a27392ba7edbe9b4c0db03"
    url = "https://caltech.box.com/shared/static/4jcz9c1lp6rt750q28kx3qvihi8393tv.gz"

[fluxnet_sites]
git-tree-sha1 = "2fc70601badf6f83dee2b84ba9c386ad041de8e2"

    [[fluxnet_sites.download]]
    sha256 = "f05b4c01b57afe9c0f59095b39cea1c0cf46b20deecd5c7afb44f474d9cd9966"
    url = "https://caltech.box.com/shared/static/otrr2y0rgjct7hqhmq214nb8qjsvqj5p.gz"

[topmodel]
git-tree-sha1 = "10855ff977cc948a92c7a83915895d27650649a1"

    [[topmodel.download]]
    sha256 = "03de8f42fedf3836c6792571f04b55fbaca321919ecd761b846286dc56bfa2e8"
    url = "https://caltech.box.com/shared/static/bfjxp72vre6b5ncm7jqf9w8hyj4ab4yr.gz"

[lehmann2008_evaporation]
git-tree-sha1 = "49386718eda19d2fa00ae6981d83948c6664057a"

    [[lehmann2008_evaporation.download]]
    sha256 = "e9603add174709a8eb7f70487bdc0f519843c03d83cb40cf07acd428f0d9d881"
    url = "https://caltech.box.com/shared/static/khhop0nvuumrtzdakemaab8hsq8emh8e.gz"

[ilamb_data]
git-tree-sha1 = "839224a62b59d73073bdb9a5c55d3dc75e30fe33"

    [[ilamb_data.download]]
    sha256 = "64a9a344ebfbb0113014178a1f93a655c401431565907c07fd33aff8860b62d6"
    url = "https://caltech.box.com/shared/static/eii2bfwfp47axfeuysgxlgzbczz27u5g.gz"
