[era5_land_forcing_data2021]
git-tree-sha1 = "ec424296df6b60cfe273ac8f981701fbbed0bd8a"

[soil_params_Gupta2020_2022]
git-tree-sha1 = "c10e8f877603bfa2c018eb2dd0c51dd078abe5df"

    [[soil_params_Gupta2020_2022.download]]
    sha256 = "6205d96ae7724c469eef5cd1cf3b99e186637427b6fb65ecc659fb808fc6cacf"
    url = "https://caltech.box.com/shared/static/7c6yx62tzjivxfmhqyy03r6e9l1glyu1.gz"
