status = [
  "buildkite/climalsm-ci",
  "ci 1.9 - ubuntu-latest",
  "ci 1.9 - macOS-latest",
  "docbuild",
  "format",
]
delete_merged_branches = true
timeout_sec = 10800
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"