name = "Ratios"
uuid = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.4.5"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"

[compat]
FixedPointNumbers = "0.5, 0.6, 0.7, 0.8"
Requires = "1"
julia = "0.7, 1"

[extensions]
RatiosFixedPointNumbersExt = "FixedPointNumbers"

[extras]
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FixedPointNumbers", "Test"]
