name = "MKL_jll"
uuid = "856f044c-d86e-5d09-b602-aeab76dc8ba7"
version = "2025.2.0+0"

[deps]
IntelOpenMP_jll = "1d5cc7b8-4909-519e-a0f8-d0f5ad9712d0"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
oneTBB_jll = "1317d2d5-d96f-522e-a858-c73665f53c3e"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
IntelOpenMP_jll = "2025.2.0"
LazyArtifacts = "< 0.0.1, 1"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
