name = "libsixel_jll"
uuid = "075b6546-f08a-558a-be8f-8157d0f608a5"
version = "1.10.5+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
JpegTurbo_jll = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
libpng_jll = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
