name = "Insolation"
uuid = "e98cc03f-d57e-4e3c-b70c-8d51efe9e0d8"
authors = ["Climate Modeling Alliance"]
version = "0.10.2"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
ClimaParams = "5c42b081-d73a-476f-9059-fd94b934656c"

[weakdeps]
ClimaParams = "5c42b081-d73a-476f-9059-fd94b934656c"

[extensions]
CreateParametersExt = "ClimaParams"

[compat]
Artifacts = "<0.0.1, 1"
Dates = "<0.0.1, 1"
DelimitedFiles = "<0.0.1, 1"
Interpolations = "0.13, 0.14, 0.15"
julia = "1.9"
ClimaParams = "1"
