name = "StackViews"
uuid = "cae243ae-269e-4f55-b966-ac2d0dc13c15"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.1.2"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
Aqua = "0.8"
Documenter = "0.27, 1"
OffsetArrays = "1"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Documenter", "Test"]
