name = "Inflate"
uuid = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
authors = ["Gunnar Farneb√§ck <gunnar@lysator.liu.se>"]
version = "0.1.5"

[compat]
CodecZlib = "0.5, 0.6, 0.7"
julia = "1"

[extras]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CodecZlib", "Random"]
