name = "Hwloc_jll"
uuid = "e33a78d0-f292-5ffc-b300-72abe9b543c8"
version = "2.12.2+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
XML2_jll = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Xorg_libpciaccess_jll = "a65dc6b1-eb27-53a1-bb3e-dea574b5389e"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
XML2_jll = "~2.13.6"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
