name = "NVTX"
uuid = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
authors = ["Simon Byrne <simonbyrne@gmail.com>"]
version = "1.0.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
JuliaNVTXCallbacks_jll = "9c1d0b0a-7046-5b2e-a33f-ea22f176ac7e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
NVTX_jll = "e98f9f5b-d649-5603-91fd-7774390e6439"

[compat]
Colors = "0.12, 0.13"
JuliaNVTXCallbacks_jll = "0.2"
NVTX_jll = "3.1.1"
julia = "1.6"

[extras]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DBInterface", "DataFrames", "SQLite", "Test"]
