name = "AliasTables"
uuid = "66dad0bd-aa9a-41b7-9441-69ab47430ed8"
authors = ["Lilith Orion Hafner <lilithhafner@gmail.com> and contributors"]
version = "1.1.3"

[deps]
PtrArrays = "43287f4e-b6f4-7ad1-bb20-aadabca52c3d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
PtrArrays = "1.1.0"
Random = "<0.0.1, 1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
RegressionTests = "2cca1867-674a-4323-b559-fc77c0bbdb31"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "OffsetArrays", "RegressionTests", "StableRNGs", "Test"]
