name = "GridLayoutBase"
uuid = "3955a311-db13-416c-9275-1d80ed98e5e9"
authors = ["Julius Krumbiegel"]
version = "0.11.2"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"

[compat]
GeometryBasics = "0.4.11, 0.5.1"
Observables = "0.3, 0.4, 0.5"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
