name = "LazyModules"
uuid = "8cdb02fc-e678-4876-92c5-9defec4f444e"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.3.1"

[compat]
julia = "1"

[extras]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Colors", "OffsetArrays", "Test"]
