name = "Glib_jll"
uuid = "7746bdde-850d-59dc-9ae8-88ece973131d"
version = "2.86.0+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Libmount_jll = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
PCRE2_jll = "efcefdf7-47ab-520b-bdef-62a2eaa19f15"
GettextRuntime_jll = "b0724c58-0f36-5564-988d-3bb0596ebc4a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Libiconv_jll = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Libffi_jll = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
Zlib_jll = "1.2.12"
PCRE2_jll = "10.42.0"
Libdl = "< 0.0.1, 1"
GettextRuntime_jll = "0.22.4"
Artifacts = "< 0.0.1, 1"
Libffi_jll = "~3.4.7"
