[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
tectonic_jll = "d7dd28d6-a5e6-559c-9131-7eb760cdacc5"

[sources]
Unitful = {path = ".."}

[compat]
Documenter = "1"
Latexify = "0.16.10"
Plots = "1"
Fontconfig = "0.4"
