name = "JpegTurbo"
uuid = "b835a17e-a41a-41e7-81f0-2f016b05efe0"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.1.6"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
JpegTurbo_jll = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
CEnum = "0.3, 0.4, 0.5"
FileIO = "1"
ImageCore = "0.8, 0.9, 0.10"
JpegTurbo_jll = "2, 3"
julia = "1.6"
TOML = "1"
