name = "HarfBuzz_jll"
uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
version = "8.5.1+0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Cairo_jll = "83423d85-b0ee-5818-9007-b63ccbeb887a"
FreeType2_jll = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Glib_jll = "7746bdde-850d-59dc-9ae8-88ece973131d"
Fontconfig_jll = "a3f928ae-7b40-5064-980b-68af3947d34b"
Graphite2_jll = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
Libffi_jll = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
Libffi_jll = "~3.4.7"
Cairo_jll = "1.18.5"
FreeType2_jll = "2.13.4"
Libdl = "< 0.0.1, 1"
Glib_jll = "2.84.0"
Artifacts = "< 0.0.1, 1"
Fontconfig_jll = "2.16.0"
Graphite2_jll = "1.3.15"
