name = "DiskArrays"
uuid = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de>"]
version = "0.4.18"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
Aqua = "0.8"
ConstructionBase = "1"
LRUCache = "1"
Mmap = "1"
OffsetArrays = "1"
Statistics = "1.9"
Suppressor = "0.2.8"
Test = "1.9"
TraceFuns = "0.2.0"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
TraceFuns = "626f57eb-f6ca-464c-8f04-384fee2a352e"

[targets]
test = ["Aqua", "Statistics", "Test", "Suppressor", "TraceFuns"]
