name = "OpenMPI_jll"
uuid = "fe0851c0-eecd-5654-98d4-656369965a5c"
version = "5.0.8+0"

[deps]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Hwloc_jll = "e33a78d0-f292-5ffc-b300-72abe9b543c8"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
MPIPreferences = "0.1"
LazyArtifacts = "< 0.0.1, 1"
Zlib_jll = "1.2.12"
Libdl = "< 0.0.1, 1"
Hwloc_jll = "2.12.0"
TOML = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
