name = "HDF5_jll"
uuid = "0234f1f7-429e-5d53-9886-15a909be8d59"
version = "1.14.6+0"

[deps]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
libaec_jll = "477f73a3-ac25-53e9-8cc3-50b2fa2566f0"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
MPICH_jll = "7cb0a576-ebde-5e09-9194-50597f1243b4"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
LibCURL_jll = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
MPItrampoline_jll = "f1f71cc9-e9ae-5b93-9b94-4fe0e1ad3748"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
OpenMPI_jll = "fe0851c0-eecd-5654-98d4-656369965a5c"
MicrosoftMPI_jll = "9237b28f-5490-5468-be7b-bb81f5f5e6cf"

[compat]
MPIPreferences = "0.1"
Zlib_jll = "1.2.12"
libaec_jll = "1.1.3"
Libdl = "< 0.0.1, 1"
LazyArtifacts = "< 0.0.1, 1"
JLLWrappers = "1.7.0"
MPICH_jll = "4.3.0 - 4"
Artifacts = "< 0.0.1, 1"
julia = "1.6"
LibCURL_jll = "7.73,8"
OpenSSL_jll = "3.0.16"
MPItrampoline_jll = "5.5.3 - 5"
TOML = "< 0.0.1, 1"
OpenMPI_jll = "4.1.8, 5"
