name = "FreeType"
uuid = "b38be410-82b0-50bf-ab77-7b57e271db43"
version = "4.1.1"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
FreeType2_jll = "d7e528f0-a631-5988-bf34-fe36492bcfd7"

[compat]
CEnum = "0.2,0.3,0.4,0.5"
FreeType2_jll = "2.10"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[targets]
test = ["Test", "Pkg"]
