name = "Blosc_jll"
uuid = "0b7ba130-8d10-5ba8-a3d6-c5182647fed9"
version = "1.21.7+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Lz4_jll = "5ced341a-0733-55b8-9ab6-a4889d929147"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Zstd_jll = "3161d3a3-bdf6-5164-811a-617609db77b4"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
Zlib_jll = "1.2.12"
Libdl = "< 0.0.1, 1"
Lz4_jll = "1.10.1"
Artifacts = "< 0.0.1, 1"
Zstd_jll = "1.5.7"
