name = "FFMPEG_jll"
uuid = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
version = "6.1.3+0"

[deps]
LAME_jll = "c1c5ebd0-6772-5130-a774-d5fcae4a789d"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
FriBidi_jll = "559328eb-81f9-559d-9380-de523a88c83c"
Opus_jll = "91d4177d-7536-5919-b921-800302f37372"
x264_jll = "1270edf5-f2f9-52d2-97e9-ab00b5d0237a"
libaom_jll = "a4ae2306-e953-59d6-aa16-d00cac43593b"
FreeType2_jll = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
libvorbis_jll = "f27f6e37-5d2b-51aa-960f-b287f2bc3b7a"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
x265_jll = "dfaa095f-4041-5dcd-9319-2fabd8486b76"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
libass_jll = "0ac62f75-1d6f-5e53-bd7c-93b484bb37c0"
libfdk_aac_jll = "f638f0a6-7fb0-5443-88ba-1cc74229b280"
Ogg_jll = "e7412a2a-1a6e-54c0-be00-318e2571c051"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
PCRE2_jll = "efcefdf7-47ab-520b-bdef-62a2eaa19f15"

[compat]
Libdl = "< 0.0.1, 1"
x264_jll = "10164.0.1"
FreeType2_jll = "2.13.4"
JLLWrappers = "1.7.0"
x265_jll = "~4.1"
Bzip2_jll = "1.0.9"
libass_jll = "0.17.4"
libfdk_aac_jll = "2.0.4"
Artifacts = "< 0.0.1, 1"
julia = "1.6"
OpenSSL_jll = "3.5.0"
PCRE2_jll = "10.42.0"
