name = "WebP"
uuid = "e3aaa7dc-3e4b-44e0-be63-ffb868ccd7c1"
authors = ["Jesper Stemann Andersen"]
version = "0.1.3"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
libwebp_jll = "c5f90fcd-3b7e-5836-afba-fc50a0988cb2"

[compat]
CEnum = "0.4, 0.5"
ColorTypes = "0.11, 0.12"
FileIO = "1"
FixedPointNumbers = "0.8"
ImageCore = "0.10"
julia = "1"
libwebp_jll = "1"

[extras]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["Downloads", "ImageIO", "Test", "TestImages"]
