name = "libzip_jll"
uuid = "337d8026-41b4-5cde-a456-74a10e5b31d1"
version = "1.11.3+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
XZ_jll = "ffd25f8a-64ca-5728-b0f7-c24cf3aae800"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Zstd_jll = "3161d3a3-bdf6-5164-811a-617609db77b4"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
OpenSSL_jll = "3.0.15"
Bzip2_jll = "1.0.8"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
