name = "ClimaUtilities"
uuid = "b3f4f4ca-9299-4f7f-bd9b-81e1242a7513"
authors = ["Gabriele Bozzola <gbozzola@caltech.edu>", "Julia Sloan <jsloan@caltech.edu>", "Kevin Phan <kphan2@caltech.edu>"]
version = "0.1.26"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
ClimaComms = "3a4d1b5c-c61d-41fd-a00a-5873ba7a1b0d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ClimaCore = "d414da3d-4745-48bb-8d80-42e94e092884"
ClimaCoreTempestRemap = "d934ef94-cdd4-4710-83d6-720549644b70"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[extensions]
ClimaUtilitiesClimaCoreExt = "ClimaCore"
ClimaUtilitiesClimaCoreInterpolationsExt = ["ClimaCore", "Interpolations"]
ClimaUtilitiesClimaCoreNCDatasetsExt = ["ClimaCore", "NCDatasets"]
ClimaUtilitiesNCDatasetsExt = "NCDatasets"
ClimaUtilitiesClimaCoreTempestRemapExt = "ClimaCoreTempestRemap"

[compat]
Adapt = "4"
Artifacts = "1"
CUDA = "5.5"
ClimaComms = "0.6.2"
ClimaCore = "0.14.23"
ClimaCoreTempestRemap = "0.3.15"
Dates = "1"
Interpolations = "0.15.1"
NCDatasets = "0.14"
julia = "1.10"
