name = "Jieko"
uuid = "ae98c720-c025-4a4a-838c-29b094483192"
authors = ["Roger-luo<rogerluo.rl18@gmail.com>"]
version = "0.2.1"

[deps]
ExproniconLite = "55351af7-c7e9-48d6-89ff-24e801d99491"

[compat]
ExproniconLite = "0.10.12"
julia = "1.6"
