name = "AxisAlgorithms"
uuid = "13072b0f-2c55-5437-9ae7-d433b7a33950"
author = ["Tim Holy <tim.holy@gmail.com>"]
version = "1.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
WoodburyMatrices = "efce3f68-66dc-5838-9240-27a6d6f5f9b6"

[compat]
LinearAlgebra = "1"
Random = "1"
SparseArrays = "1"
WoodburyMatrices = "1"
julia = "1.6"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OffsetArrays", "Test"]
