name = "FunctionWrappersWrappers"
uuid = "77dc65aa-8811-40c2-897b-53d922fa7daf"
authors = ["Chris Elrod <elrodc@gmail.com> and contributors"]
version = "0.1.3"

[deps]
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"

[compat]
FunctionWrappers = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
