name = "LayoutPointers"
uuid = "10f19ff3-798f-405d-979b-55457f8fc047"
authors = ["chriselrod <elrodc@gmail.com> and contributors"]
version = "0.1.17"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ManualMemory = "d125e4d3-2237-4719-b19c-fa641b8a4667"
SIMDTypes = "94e857df-77ce-4151-89e5-788b33177be4"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StaticArrayInterface = "0d7ed370-da01-4f52-bd93-41d350b8b718"

[compat]
ArrayInterface = "7"
LinearAlgebra = "1"
ManualMemory = "0.1.6"
SIMDTypes = "0.1"
Static = "0.8, 1"
StaticArrayInterface = "1"
Test = "1.11.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
