name = "Cairo_jll"
uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a"
version = "1.18.5+0"

[deps]
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Fontconfig_jll = "a3f928ae-7b40-5064-980b-68af3947d34b"
Xorg_libXrender_jll = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
Pixman_jll = "30392449-352a-5448-841d-b1acce4e97dc"
FreeType2_jll = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
Glib_jll = "7746bdde-850d-59dc-9ae8-88ece973131d"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Xorg_libXext_jll = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
libpng_jll = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
LZO_jll = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"

[compat]
Zlib_jll = "1.2.12"
Libdl = "< 0.0.1, 1"
Fontconfig_jll = "2.16.0"
Pixman_jll = "0.44.2"
FreeType2_jll = "2.13.4"
JLLWrappers = "1.7.0"
Bzip2_jll = "1.0.9"
Glib_jll = "2.84.0"
Artifacts = "< 0.0.1, 1"
julia = "1.6"
libpng_jll = "1.6.47"
LZO_jll = "2.10.3"
