name = "JLLWrappers"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
authors = ["Mos√® Giordano", "Elliot Saba"]
version = "1.7.1"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[compat]
Preferences = "1.2.1"
julia = "1.0.0"

[extras]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Downloads", "Pkg", "Test"]
