name = "ThreadingUtilities"
uuid = "8290d209-cae3-49c0-8002-c8c24d57dab5"
authors = ["Chris Elrod <elrodc@gmail.com> and contributors"]
version = "0.5.5"

[deps]
ManualMemory = "d125e4d3-2237-4719-b19c-fa641b8a4667"

[compat]
Aqua = "0.5"
ManualMemory = "0.1.1"
julia = "1.5"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "BenchmarkTools", "InteractiveUtils", "StaticArrays", "Test"]
