name = "CompositionsBase"
uuid = "a33af91c-f02d-484b-be07-31d278c5ca2b"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.2"

[weakdeps]
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[extensions]
CompositionsBaseInverseFunctionsExt = "InverseFunctions"

[compat]
InverseFunctions = "0.1"
julia = "1"

[extras]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Compat", "Documenter", "InverseFunctions", "Test"]
