name = "CommonDataModel"
uuid = "1fbeeb36-5f17-413c-809b-666fb144f157"
keywords = ["netcdf", "GRIB", "climate and forecast conventions", "oceanography", "meteorology", "climatology", "opendap"]
license = "MIT"
desc = "CommonDataModel is a module that defines types common to NetCDF and GRIB data"
authors = ["Alexander Barth <barth.alexander@gmail.com>"]
version = "0.3.10"

[deps]
CFTime = "179af706-886a-5703-950a-314cd64e0468"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CFTime = "0.1.1, 0.2"
DataStructures = "0.17, 0.18, 0.19"
Dates = "1"
Preferences = "1.3"
Printf = "1"
Statistics = "1"
julia = "1.6"
